/**
* @Author: eason
* @Date:   2017-05-25T20:27:21+08:00
* @Email:  uniquecolesmith@gmail.com
* @Last modified by:   eason
* @Last modified time: 2017-05-25T20:37:19+08:00
* @License: MIT
* @Copyright: Eason(uniquecolesmith@gmail.com)
*/

module.exports = {
  "/v1/login/cellphone": "/login/cellphone",
  "/v1/login": "/login",
  "/v1/login/refresh": "/login/refresh",
  "/v1/banner": "/banner",
  "/v1/playlist/catlist": "/playlist/catlist",
  "/v1/playlist/hot": "/playlist/hot",
  "/v1/personalized/newsong": "/personalized/newsong",
  "/v1/personalized": "/personalized",
  "/v1/personalized/mv": "/personalized/mv",
  "/v1/personalized/privatecontent": "/personalized/privatecontent",
  "/v1/personalized/djprogram": "/personalized/djprogram",
  "/v1/recommend/songs": "/recommend/songs",
  "/v1/recommend/dislike": "/recommend/dislike",
  "/v1/recommend/resource": "/recommend/resource",
  "/v1/playlist/tracks": "/playlist/tracks",
  "/v1/search": "/search",
  "/v1/search/multimatch": "/search/multimatch",
  "/v1/search/hot": "/search/hot",
  "/v1/search/suggest": "/search/suggest",
  "/v1/fm": "/fm",
  "/v1/lyric": "/lyric",
  "/v1/top/artist": "/top/artist",
  "/v1/top/songs": "/top/songs",
  "/v1/top/album": "/top/album",
  "/v1/top/mv": "/top/mv",
  "/v1/top/mv/first": "/top/mv/first",
  "/v1/top/playlist": "/top/playlist",
  "/v1/top/playlist/highquality": "/top/playlist/highquality",
  "/v1/simi/playlist": "/simi/playlist",
  "/v1/simi/song": "/simi/song",
  "/v1/simi/user": "/simi/user",
  "/v1/comments": "/comments",
  "/v1/artist": "/artist",
  "/v1/artist/album": "/artist/album",
  "/v1/artist/mv": "/artist/mv",
  "/v1/artist/desc": "/artist/desc",
  "/v1/artist/simi": "/artist/simi",
  "/v1/user/subcount": "/user/subcount",
  "/v1/user/cloud": "/user/cloud",
  "/v1/user/cloud/search": "/user/cloud/search",
  "/v1/mv": "/mv",
  "/v1/mv/simi": "/mv/simi",
  "/v1/mv/url": "/mv/url",
  "/v1/music/detail": "/music/detail",
  "/v1/album/detail": "/album/detail",
  "/v1/music/url": "/music/url",
  "/v1/user/detail": "/user/detail",
  "/v1/user/playlist": "/user/playlist",
  "/v1/user/radio": "/user/radio",
  "/v1/user/follows": "/user/follows",
  "/v1/follow": "/follow",
  "/v1/user/followeds": "/user/followeds",
  "/v1/playlist/detail": "/playlist/detail",
  "/v1/playlist/img": "/playlist/img",
  "/v1/daily_signin": "/daily_signin",
  "/v1/record": "/record",
  "/v1/likelist": "/likelist",
  "/v1/program/like": "/program/like",
  "/v1/djradio/catelist": "/djradio/catelist",
  "/v1/program/recommend": "/program/recommend",
  "/v1/djradio/recommend": "/djradio/recommend",
  "/v1/djradio/recommend/type": "/djradio/recommend/type",
  "/v1/djradio/hot": "/djradio/hot",
  "/v1/program/detail": "/program/detail",
  "/v1/dj/program": "/dj/program",
  "/v1/dj/detail": "/dj/detail",
  "/v1/event/get": "/event/get",
  "/v1/dj/sub": "/dj/sub",
  "/v1/resource/like": "/resource/like",
  "/v1/comment/like": "/comment/like",
  "/v1/song/tracks": "/song/tracks",
  "/v1/user/dj": "/user/dj",
  "/v1/log/web": "/log/web",
  "/v1/id2url": "/id2url",
  "/v1/toplist": "/toplist",
  "/v1/playlist/all": "/playlist/all",
  "/v1/toplist/detail": "/toplist/detail",
  "/v1/toplist/artist": "/toplist/artist",
};
